export const keywords = [
  "massagestoel kopen",
  "massagestoel online bestellen",
  "massagestoel aanbieding",
  "massagestoel reviews",
  "massagestoel vergelijken",
  "massagestoel voor thuis",
  "massagestoel voor kantoor",
  "massagestoel met garantie",
  "massagestoel met gratis levering",
  "massagestoel met installatie",
  "massagestoel met voetmassage",
  "massagestoel met neksteun",
  "massagestoel met rugmassage",
  "massagestoel met shiatsu functie",
  "massagestoel met warmtefunctie",
  "massagestoel met bluetooth",
  "massagestoel met hoofdsteun",
  "massagestoel met armsteunen",
  "beste massagestoel 2025",
  "goedkope massagestoel",
  "massagestoel aanbieding",
  "massagestoel outlet",
  "massagestoel bestellen online",
  "luxueuze massagestoelen",
  "professionele massagestoel voor thuis",
  "Shiatsu massagestoel kopen",
  "elektrische massagestoel kopen",
  "zero gravity massagestoel",
  "massagestoel met verwarming",
  "massagestoel met bluetooth speakers",
  "voordelen van een massagestoel",
  "gezondheidsvoordelen massagestoelen",
  "massagestoelen voor rugklachten",
  "massagestoelen voor nekpijn",
  "massagestoelen tegen stress",
  "welke massagestoel past bij mij",
  "verschillende soorten massagetechnieken",
  "Shiatsu massage uitgelegd",
  "massagestoel onderhoudstips",
  "massagestoel schoonmaken",
  "hoe werkt een massagestoel",
  "massage programma's massagestoel uitgelegd",
  "last van rugpijn oplossingen",
  "chronische nekklachten behandelen",
  "stress verminderen thuis",
  "burn-out herstel hulpmiddelen",
  "spierpijn verlichting thuis",
  "rugklachten voorkomen door massage",
  "bloedcirculatie verbeteren massagestoel",
  "beste massagestoel voor ouderen",
  "massagestoel voor kleine ruimtes",
  "massagestoel kantoorgebruik",
  "massagestoel voor lange mensen",
  "massagestoel met voetmassage",
  "massagestoel met stemherkenning",
  "massagestoel als cadeau idee",
  "massagestoel wellness ervaring thuis",
  "massagestoel tegen hoofdpijn",
  "hoe vaak mag je in een massagestoel zitten",
  "massagestoel kopen of huren",
  "massagestoel op afbetaling kopen"
];
